# Site settings
course_name: Social Network
course_description: ""
course_semester: "Fall 2025"

schoolname: "University of Tehran"
schoolurl: "https://ut.ac.ir"

address: |
    School of Electrical and Computer Engineering (ECE)
    University of Tehran
    North Kargar st,
    Tehran, Iran.

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%Y-%m-%d"

future: true
collections:
    events:
        output: true
        permalink: events/:year/:month/:title
    lectures:
        output: true
        permalink: lectures/:year/:month/:title
    assignments:
        output: true
        permalink: assignments/:year/:month/:title
    announcements:
        output: false

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"

plugins:
  - jekyll-sitemap
url: "https://socialnetworkut.ir"